// Copy for the storytelling sections: environment gallery, day/night
// comparison, feature chapters, hotspots, guided demo and component story.
// Merged into COPY by copy.js. Concept renders are always labelled as such.

export const STORY_COPY = {
  en: {
    galleryTitle: "A setting for every project",
    galleryText: "Buyers decide faster when they see the pergola where it will stand. Show your range in the places your customers live and work.",
    galleryConcept: "Concept renders. The live demo opens the closest matching scene.",
    gallerySelect: "Choose a setting",
    scenes: {
      garden: { name: "Garden terrace", title: "Site context sells the space", text: "A freestanding pergola set into planting and paving helps buyers judge size, shade and how the space connects to the house.", alt: "Concept render of a charcoal louvered pergola with sliding glass on a sunny garden terrace" },
      villa: { name: "Poolside villa", title: "Wall-mounted integration", text: "Fixed to the facade, the structure extends the living room toward the water without posts on the wall side.", alt: "Concept render of a wall-mounted pergola overlooking a coastal villa pool" },
      rooftop: { name: "Hospitality rooftop", title: "Larger layouts for hospitality", text: "Two bays, heaters and evening lighting show how a wider footprint works for dining and lounge seating.", alt: "Concept render of a two-bay pergola with dining and lounge seating on a rooftop at dusk" },
    },
    exploreSetting: "Explore this setting",
    exploreNote: "Opens the live {scene} scene and keeps your current design.",
    loadExample: "Load example design",
    exampleNote: "Replaces your design with an example. You can undo it.",
    exampleLoaded: "Example design loaded.",
    undo: "Undo",
    undoDone: "Your previous design is back.",
    discussEnvironment: "Discuss a custom environment",
    interest: "Interest",
    interestScene: "Custom environment like the {scene} concept",
    removeInterest: "Remove",
    openedScene: "Showing the live {scene} scene. The gallery image is a concept render.",

    compareTitle: "One space. A different atmosphere.",
    compareText: "Evening light changes how buyers picture the space. Drag the divider or switch between day and evening.",
    compareDay: "Day",
    compareEvening: "Evening",
    compareSlider: "Divider between day and evening views",
    compareDayAlt: "Concept render of a charcoal louvered pergola on a garden terrace in daylight",
    compareEveningAlt: "The same garden pergola at blue hour with warm integrated roof lighting",
    compareConcept: "Concept renders of the same terrace.",
    compareCta: "Try night lighting in 3D",
    nightApplied: "Night lighting is on in the live model. Everything else is unchanged.",

    storyTitle: "See every option in action",
    storyText: "Each option is a working part of the model. Step through them here, then try them in the configurator.",
    storyProgress: "Chapter {n} of {total}",
    storyModel: "3D model",
    storyDetail: "Detail",
    storyCaptured: "Rendered by the live configurator.",
    storyConcept: "Concept close-up.",
    storyStates: "Model states",
    chapters: {
      roof: { title: "Open the roof", text: "Louvers rotate from closed to fully open, so buyers see how much sun and shade they get before they order.", states: ["Closed", "Half open", "Open"], cta: "Set the louvers in 3D" },
      enclosure: { title: "Shape the enclosure", text: "Sliding glass stacks inside its bay and ZIP screens roll down between side rails. Every side can take its own system.", states: ["Open sides", "Glass closed", "Screen lowered"], cta: "Choose side systems in 3D" },
      atmosphere: { title: "Set the atmosphere", text: "Frame finishes, perimeter LEDs and infrared heaters turn the same structure into an evening space.", states: ["Anthracite", "Traffic white", "Warm LED", "Colour LED"], cta: "Add lighting in 3D" },
    },
    hotspotsLabel: "Feature details",
    close: "Close",
    hotspotOpen: "Show detail: {name}",
    hotspots: {
      glass: [
        ["Sliding glass", "Panels overlap and slide past each other, stacking to one side of the bay."],
        ["Floor track", "A low track guides the panels and keeps the threshold close to flush."],
        ["ZIP screen", "Fabric runs in side rails, so it stays taut and gives shade and privacy."],
        ["Perimeter LED", "A continuous strip under the beam gives even light after dark."],
      ],
      detail: [
        ["Post and beam", "Square aluminium profiles meet with a clean shadow gap."],
        ["Recessed LED", "Light sits inside the beam line rather than on its surface."],
        ["Louver blades", "Blades turn together to control light, air and rain."],
      ],
    },
    demoPlay: "Play guided demo",
    demoPause: "Pause",
    demoResume: "Resume",
    demoStop: "Stop",
    demoKeep: "Keep this setup",
    demoRestore: "Back to my design",
    demoFinished: "Demo finished. Keep the demonstrated setup or return to your design.",
    demoStopped: "Demo stopped. Your design is restored.",
    demoLabel: "Guided demo",
    demoSteps: ["Framing the roof…", "Opening the louvers…", "Sliding the glass…", "Lowering the screen…", "Switching on the lights…"],
    demoCta: "Watch the guided demo",

    componentsTitle: "Built around your product",
    componentsText: "We build your configurator from your own models, materials and rules, and we can create custom environments for your market.",
    componentsConcept: "Concept illustration of configurable components. Not an installation guide or engineering drawing.",
    componentsAlt: "Conceptual exploded view of a pergola frame, louvers, posts, glass enclosure and lighting strip",
    components: [
      ["Structure and dimensions", "Posts and beams follow your span limits. In this demo, bays split above {width} of width and {depth} of projection."],
      ["Roof and louver system", "Blade rotation, spacing and finish come from your product data."],
      ["Side enclosures", "Sliding glass, fixed glass, ZIP screens and panels, each with its own travel limits. Sliding panels open up to 75%."],
      ["Lighting and accessories", "LED options, heaters and add-ons, priced from your own grid once it is agreed."],
    ],
    serviceTitle: "What we prepare",
    service: ["3D models from your drawings or CAD", "Material and finish libraries", "Configuration and pricing rules", "Custom environments for your market"],
  },

  tr: {
    galleryTitle: "Her proje için bir ortam",
    galleryText: "Müşteriler pergolayı kurulacağı yerde gördüğünde daha hızlı karar verir. Ürün gamınızı müşterilerinizin yaşadığı ve çalıştığı yerlerde gösterin.",
    galleryConcept: "Konsept görseller. Canlı demo en yakın sahneyi açar.",
    gallerySelect: "Bir ortam seçin",
    scenes: {
      garden: { name: "Bahçe terası", title: "Alan bağlamı satışı kolaylaştırır", text: "Bitki ve zemin döşemesiyle çevrili bağımsız pergola, müşterinin ölçüyü, gölgeyi ve evle bağlantıyı değerlendirmesini sağlar.", alt: "Güneşli bahçe terasında sürgülü camlı antrasit bioklimatik pergolanın konsept görseli" },
      villa: { name: "Havuzlu villa", title: "Duvara monte entegrasyon", text: "Cepheye sabitlenen yapı, duvar tarafında dikme olmadan yaşam alanını suya doğru uzatır.", alt: "Sahil villasının havuzuna bakan duvara monte pergolanın konsept görseli" },
      rooftop: { name: "Otel ve restoran çatısı", title: "Ağırlama için geniş yerleşimler", text: "İki modül, ısıtıcılar ve akşam aydınlatması, geniş bir tabanın yemek ve lounge oturma alanında nasıl çalıştığını gösterir.", alt: "Akşamüstü çatıda yemek ve lounge oturma alanlı iki modüllü pergolanın konsept görseli" },
    },
    exploreSetting: "Bu ortamı keşfedin",
    exploreNote: "Canlı {scene} sahnesini açar, mevcut tasarımınızı korur.",
    loadExample: "Örnek tasarımı yükle",
    exampleNote: "Tasarımınızı bir örnekle değiştirir. Geri alabilirsiniz.",
    exampleLoaded: "Örnek tasarım yüklendi.",
    undo: "Geri al",
    undoDone: "Önceki tasarımınız geri geldi.",
    discussEnvironment: "Özel ortamı konuşalım",
    interest: "İlgi alanı",
    interestScene: "{scene} konseptine benzer özel ortam",
    removeInterest: "Kaldır",
    openedScene: "Canlı {scene} sahnesi gösteriliyor. Galeri görseli konsept çalışmadır.",

    compareTitle: "Tek alan. Farklı bir atmosfer.",
    compareText: "Akşam ışığı, müşterinin alanı nasıl hayal ettiğini değiştirir. Ayırıcıyı sürükleyin veya gündüz ile akşam arasında geçiş yapın.",
    compareDay: "Gündüz",
    compareEvening: "Akşam",
    compareSlider: "Gündüz ve akşam görünümleri arasındaki ayırıcı",
    compareDayAlt: "Gün ışığında bahçe terasındaki antrasit bioklimatik pergolanın konsept görseli",
    compareEveningAlt: "Aynı bahçe pergolası, mavi saatte sıcak entegre çatı aydınlatmasıyla",
    compareConcept: "Aynı terasın konsept görselleri.",
    compareCta: "Gece aydınlatmasını 3D’de deneyin",
    nightApplied: "Canlı modelde gece aydınlatması açık. Diğer her şey aynı.",

    storyTitle: "Her seçeneği çalışırken görün",
    storyText: "Her seçenek modelin çalışan bir parçasıdır. Burada adım adım inceleyin, sonra konfigüratörde deneyin.",
    storyProgress: "Bölüm {n} / {total}",
    storyModel: "3D model",
    storyDetail: "Detay",
    storyCaptured: "Canlı konfigüratörden alınan görüntüler.",
    storyConcept: "Konsept yakın plan.",
    storyStates: "Model durumları",
    chapters: {
      roof: { title: "Çatıyı açın", text: "Lameller kapalıdan tam açığa döner; müşteri sipariş vermeden önce ne kadar güneş ve gölge alacağını görür.", states: ["Kapalı", "Yarı açık", "Açık"], cta: "Lamelleri 3D’de ayarlayın" },
      enclosure: { title: "Kapalı alanı şekillendirin", text: "Sürgülü cam modül içinde toplanır, ZIP perdeler yan raylar arasında iner. Her yan kendi sistemini alabilir.", states: ["Açık yanlar", "Cam kapalı", "Perde indirilmiş"], cta: "Yan sistemleri 3D’de seçin" },
      atmosphere: { title: "Atmosferi belirleyin", text: "Gövde renkleri, çevre LED’leri ve infrared ısıtıcılar aynı yapıyı bir akşam mekânına dönüştürür.", states: ["Antrasit", "Trafik beyazı", "Sıcak LED", "Renkli LED"], cta: "3D’de aydınlatma ekleyin" },
    },
    hotspotsLabel: "Özellik detayları",
    close: "Kapat",
    hotspotOpen: "Detayı göster: {name}",
    hotspots: {
      glass: [
        ["Sürgülü cam", "Paneller birbirinin üzerinden kayar ve modülün bir yanında toplanır."],
        ["Zemin rayı", "Alçak ray panelleri yönlendirir ve eşiği neredeyse düz tutar."],
        ["ZIP perde", "Kumaş yan raylarda ilerler; gergin kalır, gölge ve mahremiyet sağlar."],
        ["Çevre LED", "Kirişin altındaki kesintisiz şerit karanlıkta eşit ışık verir."],
      ],
      detail: [
        ["Dikme ve kiriş", "Kare alüminyum profiller temiz bir gölge boşluğuyla birleşir."],
        ["Gömme LED", "Işık kirişin yüzeyinde değil, hattının içinde yer alır."],
        ["Lameller", "Lameller ışığı, havayı ve yağmuru kontrol etmek için birlikte döner."],
      ],
    },
    demoPlay: "Rehberli demoyu oynat",
    demoPause: "Duraklat",
    demoResume: "Devam et",
    demoStop: "Durdur",
    demoKeep: "Bu kurulumu koru",
    demoRestore: "Tasarımıma dön",
    demoFinished: "Demo bitti. Gösterilen kurulumu koruyun veya tasarımınıza dönün.",
    demoStopped: "Demo durduruldu. Tasarımınız geri yüklendi.",
    demoLabel: "Rehberli demo",
    demoSteps: ["Çatı görüntüleniyor…", "Lameller açılıyor…", "Cam kaydırılıyor…", "Perde indiriliyor…", "Işıklar açılıyor…"],
    demoCta: "Rehberli demoyu izleyin",

    componentsTitle: "Ürününüze göre tasarlanır",
    componentsText: "Konfigüratörünüzü kendi modelleriniz, malzemeleriniz ve kurallarınızla kuruyoruz; pazarınız için özel ortamlar da hazırlayabiliriz.",
    componentsConcept: "Yapılandırılabilir bileşenlerin konsept çizimi. Montaj kılavuzu veya mühendislik çizimi değildir.",
    componentsAlt: "Pergola gövdesi, lameller, dikmeler, cam kapama ve aydınlatma şeridinin konsept patlatılmış görünümü",
    components: [
      ["Taşıyıcı ve ölçüler", "Dikme ve kirişler açıklık sınırlarınıza uyar. Bu demoda {width} genişlik ve {depth} derinliğin üzerinde modüller bölünür."],
      ["Çatı ve lamel sistemi", "Lamel dönüşü, aralığı ve rengi ürün verilerinizden gelir."],
      ["Yan kapamalar", "Sürgülü cam, sabit cam, ZIP perde ve paneller kendi hareket sınırlarıyla. Sürgülü paneller %75’e kadar açılır."],
      ["Aydınlatma ve aksesuarlar", "LED seçenekleri, ısıtıcılar ve ekler; fiyatlar onaylanan kendi tablonuzdan."],
    ],
    serviceTitle: "Neler hazırlıyoruz",
    service: ["Çizim veya CAD dosyalarınızdan 3D modeller", "Malzeme ve renk kütüphaneleri", "Konfigürasyon ve fiyat kuralları", "Pazarınıza özel ortamlar"],
  },

  az: {
    galleryTitle: "Hər layihə üçün bir mühit",
    galleryText: "Müştərilər perqolanı quraşdırılacağı yerdə gördükdə daha tez qərar verir. Məhsul çeşidinizi müştərilərinizin yaşadığı və işlədiyi yerlərdə göstərin.",
    galleryConcept: "Konsept təsvirlər. Canlı demo ən yaxın səhnəni açır.",
    gallerySelect: "Mühit seçin",
    scenes: {
      garden: { name: "Bağ terrası", title: "Məkan konteksti satışı asanlaşdırır", text: "Bitki və daş örtüklə əhatələnmiş sərbəst perqola müştəriyə ölçünü, kölgəni və evlə əlaqəni qiymətləndirməyə kömək edir.", alt: "Günəşli bağ terrasında sürüşən şüşəli antrasit lamelli perqolanın konsept təsviri" },
      villa: { name: "Hovuzlu villa", title: "Divara birləşik inteqrasiya", text: "Fasada bərkidilən konstruksiya divar tərəfində dirək olmadan yaşayış sahəsini suya doğru uzadır.", alt: "Sahil villasının hovuzuna baxan divara birləşik perqolanın konsept təsviri" },
      rooftop: { name: "Otel və restoran damı", title: "Qonaqpərvərlik üçün geniş planlar", text: "İki modul, qızdırıcılar və axşam işıqlandırması geniş sahənin yemək və lounge oturacaqları üçün necə işlədiyini göstərir.", alt: "Axşamüstü damda yemək və lounge oturacaqlı iki modullu perqolanın konsept təsviri" },
    },
    exploreSetting: "Bu mühiti kəşf edin",
    exploreNote: "Canlı {scene} səhnəsini açır və cari dizaynınızı saxlayır.",
    loadExample: "Nümunə dizaynı yüklə",
    exampleNote: "Dizaynınızı nümunə ilə əvəz edir. Geri qaytara bilərsiniz.",
    exampleLoaded: "Nümunə dizayn yükləndi.",
    undo: "Geri qaytar",
    undoDone: "Əvvəlki dizaynınız bərpa olundu.",
    discussEnvironment: "Fərdi mühiti müzakirə edək",
    interest: "Maraq",
    interestScene: "{scene} konseptinə bənzər fərdi mühit",
    removeInterest: "Sil",
    openedScene: "Canlı {scene} səhnəsi göstərilir. Qalereya təsviri konseptdir.",

    compareTitle: "Bir məkan. Fərqli atmosfer.",
    compareText: "Axşam işığı müştərinin məkanı necə təsəvvür etdiyini dəyişir. Ayırıcını sürüşdürün və ya gündüz ilə axşam arasında keçin.",
    compareDay: "Gündüz",
    compareEvening: "Axşam",
    compareSlider: "Gündüz və axşam görünüşləri arasındakı ayırıcı",
    compareDayAlt: "Gün işığında bağ terrasındakı antrasit lamelli perqolanın konsept təsviri",
    compareEveningAlt: "Eyni bağ perqolası mavi saatda isti inteqrasiya olunmuş dam işığı ilə",
    compareConcept: "Eyni terrasın konsept təsvirləri.",
    compareCta: "Gecə işıqlandırmasını 3D-də sınayın",
    nightApplied: "Canlı modeldə gecə işıqlandırması aktivdir. Qalan hər şey dəyişməyib.",

    storyTitle: "Hər seçimi işləyərkən görün",
    storyText: "Hər seçim modelin işləyən hissəsidir. Burada addım-addım baxın, sonra konfiquratorda sınayın.",
    storyProgress: "Fəsil {n} / {total}",
    storyModel: "3D model",
    storyDetail: "Detal",
    storyCaptured: "Canlı konfiquratorun təsvirləri.",
    storyConcept: "Konsept yaxın plan.",
    storyStates: "Model vəziyyətləri",
    chapters: {
      roof: { title: "Damı açın", text: "Lamellər bağlıdan tam açığa fırlanır, müştəri sifarişdən əvvəl nə qədər günəş və kölgə alacağını görür.", states: ["Bağlı", "Yarıaçıq", "Açıq"], cta: "Lamelləri 3D-də tənzimləyin" },
      enclosure: { title: "Qapalı sahəni formalaşdırın", text: "Sürüşən şüşə modulun içində toplanır, ZIP pərdələr yan relslər arasında enir. Hər tərəf öz sistemini ala bilər.", states: ["Açıq yanlar", "Şüşə bağlı", "Pərdə endirilib"], cta: "Yan sistemləri 3D-də seçin" },
      atmosphere: { title: "Atmosferi yaradın", text: "Korpus rəngləri, perimetr LED-ləri və infraqırmızı qızdırıcılar eyni konstruksiyanı axşam məkanına çevirir.", states: ["Antrasit", "Yol ağı", "İsti LED", "Rəngli LED"], cta: "3D-də işıqlandırma əlavə edin" },
    },
    hotspotsLabel: "Xüsusiyyət detalları",
    close: "Bağla",
    hotspotOpen: "Detalı göstər: {name}",
    hotspots: {
      glass: [
        ["Sürüşən şüşə", "Panellər bir-birinin üzərindən sürüşür və modulun bir tərəfində toplanır."],
        ["Döşəmə relsi", "Alçaq rels panelləri istiqamətləndirir və astananı demək olar ki, düz saxlayır."],
        ["ZIP pərdə", "Parça yan relslərdə hərəkət edir, gərgin qalır, kölgə və məxfilik yaradır."],
        ["Perimetr LED", "Tirin altındakı fasiləsiz zolaq qaranlıqda bərabər işıq verir."],
      ],
      detail: [
        ["Dirək və tir", "Kvadrat alüminium profillər təmiz kölgə boşluğu ilə birləşir."],
        ["Gömülü LED", "İşıq tirin səthində yox, onun xəttinin içində yerləşir."],
        ["Lamellər", "Lamellər işığı, havanı və yağışı idarə etmək üçün birlikdə fırlanır."],
      ],
    },
    demoPlay: "Bələdçi demonu oynat",
    demoPause: "Dayandır",
    demoResume: "Davam et",
    demoStop: "Bitir",
    demoKeep: "Bu quruluşu saxla",
    demoRestore: "Dizaynıma qayıt",
    demoFinished: "Demo bitdi. Göstərilən quruluşu saxlayın və ya dizaynınıza qayıdın.",
    demoStopped: "Demo dayandırıldı. Dizaynınız bərpa olundu.",
    demoLabel: "Bələdçi demo",
    demoSteps: ["Dam göstərilir…", "Lamellər açılır…", "Şüşə sürüşdürülür…", "Pərdə endirilir…", "İşıqlar yandırılır…"],
    demoCta: "Bələdçi demoya baxın",

    componentsTitle: "Məhsulunuza uyğun qurulur",
    componentsText: "Konfiquratorunuzu öz modelləriniz, materiallarınız və qaydalarınızla qururuq, bazarınız üçün fərdi mühitlər də hazırlaya bilərik.",
    componentsConcept: "Konfiqurasiya olunan komponentlərin konsept təsviri. Quraşdırma təlimatı və ya mühəndislik çertyojı deyil.",
    componentsAlt: "Perqola korpusu, lamellər, dirəklər, şüşə örtük və işıq zolağının konseptual açılmış görünüşü",
    components: [
      ["Konstruksiya və ölçülər", "Dirəklər və tirlər aralıq limitlərinizə uyğundur. Bu demoda {width} en və {depth} dərinlikdən sonra modullar bölünür."],
      ["Dam və lamel sistemi", "Lamellərin fırlanması, aralığı və rəngi məhsul məlumatlarınızdan gəlir."],
      ["Yan örtüklər", "Sürüşən şüşə, sabit şüşə, ZIP pərdə və panellər öz hərəkət limitləri ilə. Sürüşən panellər 75%-ə qədər açılır."],
      ["İşıqlandırma və aksesuarlar", "LED seçimləri, qızdırıcılar və əlavələr, razılaşdırılmış öz qiymət cədvəlinizlə."],
    ],
    serviceTitle: "Nə hazırlayırıq",
    service: ["Çertyoj və ya CAD fayllarınızdan 3D modellər", "Material və rəng kitabxanaları", "Konfiqurasiya və qiymət qaydaları", "Bazarınız üçün fərdi mühitlər"],
  },
};
