// Visible copy for /pergola-configurator. English is prerendered for crawlers;
// Turkish and Azerbaijani are client-side language switches on the same URL.
//
// Service prices, delivery terms and FAQ answers are reused from
// src/data/pergolaMarketing.js so commercial claims stay in one place.
import { marketing } from "../data/pergolaMarketing.js";
import { STORY_COPY } from "./copyStory.js";

const pick = (lang, keys) => Object.fromEntries(keys.map((key) => [key, marketing[lang][key]]));
const SHARED = ["services", "scopeNote", "weeks", "deliveryText", "inputs"];

// The retired page had a sample cart and WebXR mode. Answers that described
// them are replaced so the FAQ matches what this page actually does.
function faqs(lang, overrides) {
  return marketing[lang].faqs.map((item, index) => overrides[index] || item);
}

const en = {
  ...pick("en", SHARED),
  htmlLang: "en",
  title: "3D Pergola Configurator Software for Manufacturers | Configuro",
  skip: "Skip to content",
  nav: { configurator: "Configurator", features: "Features", pricing: "Pricing", faq: "FAQ" },
  language: "Language",
  ctaTry: "Try the configurator",
  ctaQuote: "Request a quote",
  home: "Configuro home",

  heroEyebrow: "Pergola configurator software",
  heroTitle: "A 3D pergola configurator for your website",
  heroText: "Buyers size, finish and equip your pergolas in real time, then send you a quote-ready specification.",
  heroAlt: "Concept render of an anthracite louvered pergola with sliding glass beside a pool terrace",
  heroCaption: "Concept render. The configurator below is a live demo.",
  heroFacts: ["Real-time 3D in the browser", "Built on your product rules", "From $2,000 for simple projects"],

  configTitle: "Configure a louvered pergola",
  configText: "A working demo with real product rules: bay spans, glass travel and wall mounting. Your version runs on your own range.",
  tabs: { size: "Size", roof: "Roof", sides: "Sides", extras: "Extras", scene: "Scene" },
  tabsLabel: "Configuration steps",
  width: "Width",
  depth: "Projection",
  height: "Height",
  mount: "Installation",
  mounts: { freestanding: "Freestanding", wall: "Wall-mounted" },
  units: "Units",
  unitNames: { imperial: "Feet", metric: "Metric" },
  bayNoteX: "Wider than {size}: an intermediate post line is added.",
  bayNoteZ: "Deeper than {size}: a middle post is added on each side.",
  roof: "Louver angle",
  roofEnds: ["Closed", "Open"],
  finish: "Frame finish",
  blade: "Louver finish",
  bladeMatch: "Match frame",
  finishNames: { ral7016: "Anthracite grey", ral9005: "Jet black", ral9016: "Traffic white", ral9006: "White aluminium", ral8019: "Grey brown", ral1015: "Light ivory" },
  side: "Side",
  sideNames: { front: "Front", right: "Right", rear: "Back", left: "Left" },
  systems: { none: "Open", sliding: "Sliding glass", fixed: "Fixed glass", zip: "ZIP screen", panel: "Composite panel" },
  systemHints: { none: "No side system", sliding: "Panels stack up to 75% open", fixed: "3 or 4 panes per bay", zip: "Rolls down between side rails", panel: "Solid aluminium composite" },
  wallSide: "This is the wall side, so it has no posts or side system.",
  planLabel: "Plan view of the side systems",
  slidingOpen: "Glass opening",
  zipOpen: "Screen opening",
  led: "Perimeter LED",
  ledModes: { off: "Off", warm: "Warm white", color: "Colour" },
  ledHue: "LED colour",
  ledLevel: "Brightness",
  heaters: "Infrared heaters",
  heatersNote: "Mounted under the side beams, facing in.",
  environment: "Setting",
  environments: { studio: "Studio", patio: "Patio", pool: "Poolside", deck: "Deck", rooftop: "Rooftop" },
  time: "Light",
  times: { day: "Day", night: "Night" },

  camera: "Camera views",
  views: { overview: "Overview", front: "Front", side: "Side", top: "Top", inside: "Inside", detail: "Detail" },
  zoomIn: "Zoom in",
  zoomOut: "Zoom out",
  resetView: "Reset view",
  viewerLabel: "Interactive 3D model of your pergola",
  viewerKeys: "Arrow keys rotate the model. Plus and minus zoom.",
  viewerHintPointer: "Drag to rotate",
  viewerHintTouch: "Swipe sideways to rotate",
  viewerLoading: "Loading 3D model…",
  viewerSceneLoading: "Loading setting…",
  viewerSceneError: "This setting could not load, so the studio is shown.",
  viewerError: "3D is not available on this device. Every option, the summary and the quote request still work.",
  viewerRetry: "Try 3D again",
  viewerStart: "Load 3D view",
  posterAlt: "Preview render of the default pergola configuration",

  summary: "Your design",
  code: "Design code",
  summarySize: "Footprint",
  summaryHeight: "Height",
  summaryStructure: "Structure",
  summaryBays: "bays: {bays}, posts: {posts}",
  summaryRoof: "Louvers",
  summarySides: "Sides",
  summaryLighting: "Lighting",
  summaryHeaters: "Heaters",
  summaryScene: "Scene",
  none: "None",
  estimate: "Illustrative estimate",
  estimateNote: "Demo calculation with placeholder rates. Not a pergola quotation and not the price of Configuro’s software.",
  estimateLines: { structure: "Structure", led: "Lighting", heaters: "Heaters", side: "{side} side" },
  share: "Copy share link",
  shareDone: "Share link copied.",
  shareFallback: "Copy this link to share your design:",
  snapshot: "Save image",
  snapshotDone: "Image saved to your downloads.",
  snapshotUnavailable: "Images need the 3D view. Load it first.",
  spec: "Download spec sheet",
  specDone: "Spec sheet downloaded.",
  resetDesign: "Reset design",
  resetDone: "Design reset to the default.",
  linkInvalid: "That design link was not recognised, so the default design is shown.",
  linkLegacy: "This older design link was converted for the new configurator.",
  specTitle: "Pergola specification",
  specDisclaimer: "Generated by the Configuro pergola configurator demo. Dimensions and options are illustrative and must be confirmed by the manufacturer.",
  specOpen: "Open this design",

  featuresTitle: "What your buyers can do",
  features: [
    ["Size it to the site", "Width, projection and height follow the spans your range can build. Extra posts appear where the rules need them."],
    ["Open the roof and slide the glass", "Louvers, sliding glass and ZIP screens move in place, so buyers see how the space works."],
    ["See it by day or at night", "Switch the setting and the light. The LED system glows under the roof after dark."],
    ["Send a quote-ready brief", "Every choice travels with the inquiry as a short design code, a spec sheet and an image."],
  ],
  nightAlt: "Concept render of the pergola at dusk with warm LED lighting under the louvers",
  detailAlt: "Close-up render of an anthracite post, beam and louvers with an integrated LED strip",

  rulesTitle: "Built on your product rules",
  rulesText: "This demo uses the span, glass and mounting rules of a real louvered pergola range. Your configurator uses yours.",
  rules: [
    ["Spans", "Bays split above {width} of width and {depth} of projection, and posts are added automatically."],
    ["Glass", "Sliding panels open up to 75%, so the stack always stays inside its bay."],
    ["Mounting", "Wall-mounted structures drop the wall-side posts and side system."],
    ["Pricing", "Live estimates can follow your own price grid once it is supplied and agreed."],
  ],

  processTitle: "From product files to launch",
  week: "Week",
  pricingTitle: "Configurator pricing",
  pricingText: "What it costs to build your configurator. Pergola prices in the demo are illustrative only.",
  startingAt: "From",

  faqTitle: "Questions, answered",
  faqs: faqs("en", {
    3: ["Can you connect Shopify, a CRM or our quotation system?", "These can be included in a custom scope after we review your platform and the data flow you need. This demo sends requests to Configuro’s own lead inbox."],
    4: ["Do customers need special hardware?", "No. The configurator runs in current mobile and desktop browsers with touch, mouse or keyboard. The inside camera shows the space at human scale without a headset."],
  }),

  quoteTitle: "Request a quote",
  quoteText: "Tell us about your range and your website. We reply within one business day with questions or a fixed-price offer.",
  form: {
    name: "Full name",
    email: "Work email",
    company: "Company",
    website: "Website",
    optional: "optional",
    role: "Your business",
    roles: { manufacturer: "Manufacturer", dealer: "Dealer or distributor", installer: "Installer", other: "Other" },
    message: "What should your configurator do?",
    messageHint: "Products, options, languages and where leads should go.",
    namePlaceholder: "Alex Morgan",
    emailPlaceholder: "alex@company.com",
    companyPlaceholder: "Company name",
    websitePlaceholder: "company.com",
    attach: "Attach my current design",
    attachNote: "Adds design code {code} and its specification to your request.",
    consent: "I agree that Configuro stores these details to respond to this request.",
    privacyLink: "How we handle your data",
    submit: "Request a quote",
    sending: "Sending…",
    successTitle: "Request received",
    successText: "Thank you. We reply within one business day.",
    reference: "Reference",
    another: "Send another request",
    error: "Your request could not be sent. Check your connection and try again, or email hello@configuro.studio.",
    retry: "Try again",
    emailInstead: "Email us instead",
    required: "This field is required.",
    badEmail: "Enter a valid email address, like alex@company.com.",
    badUrl: "Enter a valid website address, like company.com.",
    consentRequired: "Please confirm so we can store your request.",
    fixErrors: "Please fix the highlighted fields.",
  },

  privacyTitle: "Privacy",
  privacy: [
    "When you request a quote we collect the details you enter, the design you attach and how you reached this page, such as an ad campaign tag. We use them only to answer your request and prepare an offer.",
    "Requests are stored in Configuro’s lead database and CRM. Analytics and ad measurement load only if you accept them, and they never receive your name, email address or message.",
    "To see or delete your data, email hello@configuro.studio.",
  ],
  consentText: "We use analytics and ad measurement to learn which campaigns bring useful inquiries. They load only if you accept.",
  consentAccept: "Accept",
  consentDecline: "Decline",
  consentSettings: "Privacy settings",

  footerNote: "Configuro designs and builds 3D configurators. Pergola renders and demo products are illustrative.",
  footerLinks: { services: "Services", work: "Work", guide: "Configurator guide", contact: "Contact" },
};

const tr = {
  ...pick("tr", SHARED),
  htmlLang: "tr",
  title: "Üreticiler için 3D Pergola Konfigüratörü | Configuro",
  skip: "İçeriğe geç",
  nav: { configurator: "Konfigüratör", features: "Özellikler", pricing: "Fiyatlar", faq: "SSS" },
  language: "Dil",
  ctaTry: "Konfigüratörü deneyin",
  ctaQuote: "Teklif isteyin",
  home: "Configuro ana sayfa",

  heroEyebrow: "Pergola konfigüratör yazılımı",
  heroTitle: "Web siteniz için 3D pergola konfigüratörü",
  heroText: "Müşterileriniz pergolanızın ölçüsünü, rengini ve donanımını anında seçer, size teklife hazır bir şartname gönderir.",
  heroAlt: "Havuz terasında sürgülü camlı antrasit bioklimatik pergolanın konsept görseli",
  heroCaption: "Konsept görsel. Aşağıdaki konfigüratör canlı bir demodur.",
  heroFacts: ["Tarayıcıda gerçek zamanlı 3D", "Kendi ürün kurallarınızla", "Basit projeler 2.000 USD’den"],

  configTitle: "Bioklimatik pergola tasarlayın",
  configText: "Gerçek ürün kurallarıyla çalışan bir demo: modül açıklıkları, cam hareketi ve duvara montaj. Sizin sürümünüz kendi ürün gamınızla çalışır.",
  tabs: { size: "Ölçü", roof: "Çatı", sides: "Yanlar", extras: "Ekstralar", scene: "Sahne" },
  tabsLabel: "Konfigürasyon adımları",
  width: "Genişlik",
  depth: "Derinlik",
  height: "Yükseklik",
  mount: "Montaj",
  mounts: { freestanding: "Bağımsız", wall: "Duvara monte" },
  units: "Birim",
  unitNames: { imperial: "Feet", metric: "Metrik" },
  bayNoteX: "{size} genişliğin üzerinde ara dikme hattı eklenir.",
  bayNoteZ: "{size} derinliğin üzerinde her iki yana orta dikme eklenir.",
  roof: "Lamel açısı",
  roofEnds: ["Kapalı", "Açık"],
  finish: "Gövde rengi",
  blade: "Lamel rengi",
  bladeMatch: "Gövdeyle aynı",
  finishNames: { ral7016: "Antrasit gri", ral9005: "Siyah", ral9016: "Trafik beyazı", ral9006: "Beyaz alüminyum", ral8019: "Gri kahverengi", ral1015: "Açık fildişi" },
  side: "Yan",
  sideNames: { front: "Ön", right: "Sağ", rear: "Arka", left: "Sol" },
  systems: { none: "Açık", sliding: "Sürgülü cam", fixed: "Sabit cam", zip: "ZIP perde", panel: "Kompozit panel" },
  systemHints: { none: "Yan sistem yok", sliding: "Paneller %75’e kadar açılır", fixed: "Modül başına 3 veya 4 cam", zip: "Yan raylar arasında iner", panel: "Dolu alüminyum kompozit" },
  wallSide: "Bu duvar tarafıdır; dikme veya yan sistem yoktur.",
  planLabel: "Yan sistemlerin plan görünümü",
  slidingOpen: "Cam açıklığı",
  zipOpen: "Perde açıklığı",
  led: "Çevre LED",
  ledModes: { off: "Kapalı", warm: "Sıcak beyaz", color: "Renkli" },
  ledHue: "LED rengi",
  ledLevel: "Parlaklık",
  heaters: "Infrared ısıtıcılar",
  heatersNote: "Yan kirişlerin altına, içe bakacak şekilde monte edilir.",
  environment: "Ortam",
  environments: { studio: "Stüdyo", patio: "Veranda", pool: "Havuz kenarı", deck: "Ahşap teras", rooftop: "Çatı terası" },
  time: "Işık",
  times: { day: "Gündüz", night: "Gece" },

  camera: "Kamera açıları",
  views: { overview: "Genel", front: "Ön", side: "Yan", top: "Üst", inside: "İçeriden", detail: "Detay" },
  zoomIn: "Yakınlaştır",
  zoomOut: "Uzaklaştır",
  resetView: "Görünümü sıfırla",
  viewerLabel: "Pergolanızın etkileşimli 3D modeli",
  viewerKeys: "Ok tuşları modeli döndürür. Artı ve eksi yakınlaştırır.",
  viewerHintPointer: "Döndürmek için sürükleyin",
  viewerHintTouch: "Döndürmek için yana kaydırın",
  viewerLoading: "3D model yükleniyor…",
  viewerSceneLoading: "Ortam yükleniyor…",
  viewerSceneError: "Bu ortam yüklenemedi, stüdyo gösteriliyor.",
  viewerError: "Bu cihazda 3D kullanılamıyor. Tüm seçenekler, özet ve teklif talebi çalışmaya devam eder.",
  viewerRetry: "3D’yi tekrar dene",
  viewerStart: "3D görünümü yükle",
  posterAlt: "Varsayılan pergola konfigürasyonunun önizleme görseli",

  summary: "Tasarımınız",
  code: "Tasarım kodu",
  summarySize: "Taban ölçüsü",
  summaryHeight: "Yükseklik",
  summaryStructure: "Taşıyıcı",
  summaryBays: "modül: {bays}, dikme: {posts}",
  summaryRoof: "Lameller",
  summarySides: "Yanlar",
  summaryLighting: "Aydınlatma",
  summaryHeaters: "Isıtıcılar",
  summaryScene: "Sahne",
  none: "Yok",
  estimate: "Örnek fiyat hesabı",
  estimateNote: "Örnek birim fiyatlarla yapılan demo hesabıdır. Pergola teklifi veya Configuro yazılım fiyatı değildir.",
  estimateLines: { structure: "Taşıyıcı", led: "Aydınlatma", heaters: "Isıtıcılar", side: "{side} yan" },
  share: "Paylaşım bağlantısını kopyala",
  shareDone: "Paylaşım bağlantısı kopyalandı.",
  shareFallback: "Tasarımınızı paylaşmak için bu bağlantıyı kopyalayın:",
  snapshot: "Görseli kaydet",
  snapshotDone: "Görsel indirilenlere kaydedildi.",
  snapshotUnavailable: "Görsel için 3D görünüm gerekir. Önce yükleyin.",
  spec: "Şartnameyi indir",
  specDone: "Şartname indirildi.",
  resetDesign: "Tasarımı sıfırla",
  resetDone: "Tasarım varsayılana döndü.",
  linkInvalid: "Tasarım bağlantısı tanınmadı; varsayılan tasarım gösteriliyor.",
  linkLegacy: "Eski tasarım bağlantısı yeni konfigüratöre dönüştürüldü.",
  specTitle: "Pergola şartnamesi",
  specDisclaimer: "Configuro pergola konfigüratör demosu ile oluşturuldu. Ölçü ve seçenekler örnek amaçlıdır ve üretici tarafından onaylanmalıdır.",
  specOpen: "Bu tasarımı aç",

  featuresTitle: "Müşterileriniz neler yapabilir",
  features: [
    ["Alana göre ölçülendirme", "Genişlik, derinlik ve yükseklik ürün gamınızın açıklıklarına uyar. Kurallar gerektirdiğinde dikmeler eklenir."],
    ["Çatıyı açın, camı kaydırın", "Lameller, sürgülü camlar ve ZIP perdeler yerinde hareket eder; müşteri alanın nasıl çalıştığını görür."],
    ["Gündüz ve gece görün", "Ortamı ve ışığı değiştirin. Karanlıkta LED sistemi çatının altında yanar."],
    ["Teklife hazır talep gönderin", "Her seçim talebe kısa bir tasarım kodu, şartname ve görselle eklenir."],
  ],
  nightAlt: "Lameller altında sıcak LED aydınlatmalı pergolanın akşam konsept görseli",
  detailAlt: "Entegre LED şeritli antrasit dikme, kiriş ve lamellerin yakın plan görseli",

  rulesTitle: "Kendi ürün kurallarınızla",
  rulesText: "Bu demo gerçek bir bioklimatik pergola serisinin açıklık, cam ve montaj kurallarını kullanır. Sizin konfigüratörünüz kendi kurallarınızı kullanır.",
  rules: [
    ["Açıklıklar", "{width} genişlik ve {depth} derinliğin üzerinde modüller bölünür, dikmeler otomatik eklenir."],
    ["Cam", "Sürgülü paneller %75’e kadar açılır; paket her zaman modülün içinde kalır."],
    ["Montaj", "Duvara monte yapılarda duvar tarafındaki dikmeler ve yan sistem kaldırılır."],
    ["Fiyat", "Canlı fiyat hesabı, sağlanıp onaylandığında kendi fiyat tablonuzu kullanabilir."],
  ],

  processTitle: "Ürün dosyalarından yayına",
  week: "Hafta",
  pricingTitle: "Konfigüratör fiyatları",
  pricingText: "Konfigüratörünüzün yapım maliyeti. Demodaki pergola fiyatları yalnızca örnektir.",
  startingAt: "Başlangıç",

  faqTitle: "Sık sorulan sorular",
  faqs: faqs("tr", {
    3: ["Shopify, CRM veya teklif sistemimizi bağlayabilir misiniz?", "Platformunuz ve veri akışı incelendikten sonra özel kapsama dahil edilebilir. Bu demo talepleri Configuro’nun kendi talep kutusuna gönderir."],
    4: ["Müşterilerin özel donanıma ihtiyacı var mı?", "Hayır. Konfigüratör güncel mobil ve masaüstü tarayıcılarda dokunmatik, fare veya klavye ile çalışır. İçeriden kamera, alanı gözlük olmadan insan ölçeğinde gösterir."],
  }),

  quoteTitle: "Teklif isteyin",
  quoteText: "Ürün gamınızı ve web sitenizi anlatın. Bir iş günü içinde sorularımızla veya sabit fiyatlı teklifle dönüş yapıyoruz.",
  form: {
    name: "Ad soyad",
    email: "İş e-postası",
    company: "Şirket",
    website: "Web sitesi",
    optional: "isteğe bağlı",
    role: "İşletmeniz",
    roles: { manufacturer: "Üretici", dealer: "Bayi veya distribütör", installer: "Montaj firması", other: "Diğer" },
    message: "Konfigüratörünüz neler yapmalı?",
    messageHint: "Ürünler, seçenekler, diller ve taleplerin nereye gideceği.",
    namePlaceholder: "Deniz Yılmaz",
    emailPlaceholder: "deniz@firma.com",
    companyPlaceholder: "Şirket adı",
    websitePlaceholder: "firma.com",
    attach: "Mevcut tasarımımı ekle",
    attachNote: "Talebinize {code} tasarım kodunu ve şartnamesini ekler.",
    consent: "Configuro’nun bu talebe yanıt vermek için bilgilerimi saklamasını kabul ediyorum.",
    privacyLink: "Verilerinizi nasıl kullanıyoruz",
    submit: "Teklif isteyin",
    sending: "Gönderiliyor…",
    successTitle: "Talebiniz alındı",
    successText: "Teşekkürler. Bir iş günü içinde yanıt veriyoruz.",
    reference: "Referans",
    another: "Yeni talep gönder",
    error: "Talebiniz gönderilemedi. Bağlantınızı kontrol edip tekrar deneyin veya hello@configuro.studio adresine yazın.",
    retry: "Tekrar dene",
    emailInstead: "E-posta ile yazın",
    required: "Bu alan zorunludur.",
    badEmail: "Geçerli bir e-posta girin, örneğin deniz@firma.com.",
    badUrl: "Geçerli bir web adresi girin, örneğin firma.com.",
    consentRequired: "Talebinizi saklayabilmemiz için lütfen onaylayın.",
    fixErrors: "Lütfen işaretli alanları düzeltin.",
  },

  privacyTitle: "Gizlilik",
  privacy: [
    "Teklif istediğinizde girdiğiniz bilgileri, eklediğiniz tasarımı ve bu sayfaya nasıl ulaştığınızı (örneğin reklam kampanyası etiketi) toplarız. Bunları yalnızca talebinize yanıt vermek ve teklif hazırlamak için kullanırız.",
    "Talepler Configuro’nun müşteri adayı veritabanında ve CRM sisteminde saklanır. Analitik ve reklam ölçümü yalnızca kabul ederseniz yüklenir ve adınızı, e-postanızı veya mesajınızı asla almaz.",
    "Verilerinizi görmek veya sildirmek için hello@configuro.studio adresine yazın.",
  ],
  consentText: "Hangi kampanyaların faydalı talepler getirdiğini anlamak için analitik ve reklam ölçümü kullanıyoruz. Yalnızca kabul ederseniz yüklenir.",
  consentAccept: "Kabul et",
  consentDecline: "Reddet",
  consentSettings: "Gizlilik ayarları",

  footerNote: "Configuro 3D konfigüratörler tasarlar ve geliştirir. Pergola görselleri ve demo ürünler örnek amaçlıdır.",
  footerLinks: { services: "Hizmetler", work: "Çalışmalar", guide: "Konfigüratör rehberi", contact: "İletişim" },
};

const az = {
  ...pick("az", SHARED),
  htmlLang: "az",
  title: "İstehsalçılar üçün 3D Perqola Konfiquratoru | Configuro",
  skip: "Məzmuna keç",
  nav: { configurator: "Konfiqurator", features: "İmkanlar", pricing: "Qiymətlər", faq: "Suallar" },
  language: "Dil",
  ctaTry: "Konfiquratoru sınayın",
  ctaQuote: "Təklif istəyin",
  home: "Configuro ana səhifə",

  heroEyebrow: "Perqola konfiqurator proqramı",
  heroTitle: "Saytınız üçün 3D perqola konfiquratoru",
  heroText: "Müştərilər perqolanızın ölçüsünü, rəngini və avadanlığını dərhal seçir, sizə təklifə hazır spesifikasiya göndərir.",
  heroAlt: "Hovuz terrasında sürüşən şüşəli antrasit lamelli perqolanın konsept təsviri",
  heroCaption: "Konsept təsvir. Aşağıdakı konfiqurator canlı demodur.",
  heroFacts: ["Brauzerdə real vaxt 3D", "Öz məhsul qaydalarınızla", "Sadə layihələr 2 000 ABŞ dollarından"],

  configTitle: "Lamelli perqola qurun",
  configText: "Real məhsul qaydaları ilə işləyən demo: modul aralıqları, şüşənin hərəkəti və divara montaj. Sizin versiyanız öz məhsul çeşidinizlə işləyir.",
  tabs: { size: "Ölçü", roof: "Dam", sides: "Yanlar", extras: "Əlavələr", scene: "Səhnə" },
  tabsLabel: "Konfiqurasiya addımları",
  width: "En",
  depth: "Dərinlik",
  height: "Hündürlük",
  mount: "Quraşdırma",
  mounts: { freestanding: "Sərbəst", wall: "Divara birləşik" },
  units: "Vahid",
  unitNames: { imperial: "Fut", metric: "Metrik" },
  bayNoteX: "{size} endən böyük olduqda aralıq dirək xətti əlavə olunur.",
  bayNoteZ: "{size} dərinlikdən böyük olduqda hər iki yana orta dirək əlavə olunur.",
  roof: "Lamel bucağı",
  roofEnds: ["Bağlı", "Açıq"],
  finish: "Korpus rəngi",
  blade: "Lamel rəngi",
  bladeMatch: "Korpusla eyni",
  finishNames: { ral7016: "Antrasit boz", ral9005: "Qara", ral9016: "Yol ağı", ral9006: "Ağ alüminium", ral8019: "Boz qəhvəyi", ral1015: "Açıq fil sümüyü" },
  side: "Yan",
  sideNames: { front: "Ön", right: "Sağ", rear: "Arxa", left: "Sol" },
  systems: { none: "Açıq", sliding: "Sürüşən şüşə", fixed: "Sabit şüşə", zip: "ZIP pərdə", panel: "Kompozit panel" },
  systemHints: { none: "Yan sistem yoxdur", sliding: "Panellər 75%-ə qədər açılır", fixed: "Hər modulda 3 və ya 4 şüşə", zip: "Yan relslər arasında enir", panel: "Bütöv alüminium kompozit" },
  wallSide: "Bu divar tərəfidir, dirək və yan sistem yoxdur.",
  planLabel: "Yan sistemlərin plan görünüşü",
  slidingOpen: "Şüşənin açılması",
  zipOpen: "Pərdənin açılması",
  led: "Perimetr LED",
  ledModes: { off: "Söndürülüb", warm: "İsti ağ", color: "Rəngli" },
  ledHue: "LED rəngi",
  ledLevel: "Parlaqlıq",
  heaters: "İnfraqırmızı qızdırıcılar",
  heatersNote: "Yan tirlərin altına, içəriyə baxan şəkildə quraşdırılır.",
  environment: "Mühit",
  environments: { studio: "Studiya", patio: "Həyət", pool: "Hovuz kənarı", deck: "Taxta terras", rooftop: "Dam terrası" },
  time: "İşıq",
  times: { day: "Gündüz", night: "Gecə" },

  camera: "Kamera görünüşləri",
  views: { overview: "Ümumi", front: "Ön", side: "Yan", top: "Üst", inside: "İçəridən", detail: "Detal" },
  zoomIn: "Yaxınlaşdır",
  zoomOut: "Uzaqlaşdır",
  resetView: "Görünüşü sıfırla",
  viewerLabel: "Perqolanızın interaktiv 3D modeli",
  viewerKeys: "Ox düymələri modeli fırladır. Plus və minus yaxınlaşdırır.",
  viewerHintPointer: "Fırlatmaq üçün sürüşdürün",
  viewerHintTouch: "Fırlatmaq üçün yana sürüşdürün",
  viewerLoading: "3D model yüklənir…",
  viewerSceneLoading: "Mühit yüklənir…",
  viewerSceneError: "Bu mühit yüklənmədi, studiya göstərilir.",
  viewerError: "Bu cihazda 3D mövcud deyil. Bütün seçimlər, xülasə və təklif sorğusu işləməyə davam edir.",
  viewerRetry: "3D-ni yenidən sına",
  viewerStart: "3D görünüşü yüklə",
  posterAlt: "Standart perqola konfiqurasiyasının önizləmə təsviri",

  summary: "Dizaynınız",
  code: "Dizayn kodu",
  summarySize: "Oturacaq ölçüsü",
  summaryHeight: "Hündürlük",
  summaryStructure: "Konstruksiya",
  summaryBays: "modul: {bays}, dirək: {posts}",
  summaryRoof: "Lamellər",
  summarySides: "Yanlar",
  summaryLighting: "İşıqlandırma",
  summaryHeaters: "Qızdırıcılar",
  summaryScene: "Səhnə",
  none: "Yoxdur",
  estimate: "Nümunə qiymət hesabı",
  estimateNote: "Nümunə tariflərlə demo hesablamasıdır. Perqola təklifi və ya Configuro proqram xidmətinin qiyməti deyil.",
  estimateLines: { structure: "Konstruksiya", led: "İşıqlandırma", heaters: "Qızdırıcılar", side: "{side} yan" },
  share: "Paylaşma keçidini kopyala",
  shareDone: "Paylaşma keçidi kopyalandı.",
  shareFallback: "Dizaynınızı paylaşmaq üçün bu keçidi kopyalayın:",
  snapshot: "Şəkli yadda saxla",
  snapshotDone: "Şəkil endirilənlərə yadda saxlanıldı.",
  snapshotUnavailable: "Şəkil üçün 3D görünüş lazımdır. Əvvəlcə onu yükləyin.",
  spec: "Spesifikasiyanı endir",
  specDone: "Spesifikasiya endirildi.",
  resetDesign: "Dizaynı sıfırla",
  resetDone: "Dizayn standart vəziyyətə qaytarıldı.",
  linkInvalid: "Dizayn keçidi tanınmadı, standart dizayn göstərilir.",
  linkLegacy: "Köhnə dizayn keçidi yeni konfiquratora çevrildi.",
  specTitle: "Perqola spesifikasiyası",
  specDisclaimer: "Configuro perqola konfiqurator demosu ilə yaradılıb. Ölçülər və seçimlər nümunədir və istehsalçı tərəfindən təsdiqlənməlidir.",
  specOpen: "Bu dizaynı aç",

  featuresTitle: "Müştəriləriniz nə edə bilər",
  features: [
    ["Ərazinə uyğun ölçü", "En, dərinlik və hündürlük məhsul çeşidinizin aralıqlarına uyğunlaşır. Qaydalar tələb etdikdə dirəklər əlavə olunur."],
    ["Damı açın, şüşəni sürüşdürün", "Lamellər, sürüşən şüşələr və ZIP pərdələr yerində hərəkət edir, müştəri məkanın necə işlədiyini görür."],
    ["Gündüz və gecə görün", "Mühiti və işığı dəyişin. Qaranlıqda LED sistemi damın altında yanır."],
    ["Təklifə hazır müraciət göndərin", "Hər seçim müraciətə qısa dizayn kodu, spesifikasiya və şəkil ilə əlavə olunur."],
  ],
  nightAlt: "Lamellərin altında isti LED işıqlı perqolanın axşam konsept təsviri",
  detailAlt: "İnteqrasiya olunmuş LED zolaqlı antrasit dirək, tir və lamellərin yaxın planı",

  rulesTitle: "Öz məhsul qaydalarınızla",
  rulesText: "Bu demo real lamelli perqola çeşidinin aralıq, şüşə və montaj qaydalarından istifadə edir. Sizin konfiquratorunuz öz qaydalarınızla işləyir.",
  rules: [
    ["Aralıqlar", "{width} en və {depth} dərinlikdən sonra modullar bölünür, dirəklər avtomatik əlavə olunur."],
    ["Şüşə", "Sürüşən panellər 75%-ə qədər açılır, paket həmişə modulun içində qalır."],
    ["Montaj", "Divara birləşik konstruksiyalarda divar tərəfindəki dirəklər və yan sistem çıxarılır."],
    ["Qiymət", "Canlı qiymət hesabı təqdim edilib razılaşdırıldıqdan sonra öz qiymət cədvəlinizə əsaslana bilər."],
  ],

  processTitle: "Məhsul fayllarından yayıma",
  week: "Həftə",
  pricingTitle: "Konfiqurator qiymətləri",
  pricingText: "Konfiquratorunuzun hazırlanma dəyəri. Demodakı perqola qiymətləri yalnız nümunədir.",
  startingAt: "Başlanğıc",

  faqTitle: "Suallar və cavablar",
  faqs: faqs("az", {
    3: ["Shopify, CRM və ya təklif sistemimizi bağlaya bilərsiniz?", "Platformanız və məlumat axını yoxlanıldıqdan sonra fərdi iş həcminə daxil edilə bilər. Bu demo müraciətləri Configuro-nun öz müraciət qutusuna göndərir."],
    4: ["Müştərilərə xüsusi avadanlıq lazımdır?", "Xeyr. Konfiqurator müasir mobil və masaüstü brauzerlərdə toxunma, siçan və ya klaviatura ilə işləyir. İçəridən kamera məkanı eynəksiz insan miqyasında göstərir."],
  }),

  quoteTitle: "Təklif istəyin",
  quoteText: "Məhsul çeşidiniz və saytınız barədə yazın. Bir iş günü ərzində suallarımızla və ya sabit qiymətli təkliflə cavab veririk.",
  form: {
    name: "Ad soyad",
    email: "İş e-poçtu",
    company: "Şirkət",
    website: "Sayt",
    optional: "istəyə bağlı",
    role: "Biznesiniz",
    roles: { manufacturer: "İstehsalçı", dealer: "Diler və ya distribyutor", installer: "Quraşdırma şirkəti", other: "Digər" },
    message: "Konfiquratorunuz nə etməlidir?",
    messageHint: "Məhsullar, seçimlər, dillər və müraciətlərin hara göndəriləcəyi.",
    namePlaceholder: "Nigar Həsənova",
    emailPlaceholder: "nigar@sirket.az",
    companyPlaceholder: "Şirkət adı",
    websitePlaceholder: "sirket.az",
    attach: "Cari dizaynımı əlavə et",
    attachNote: "Müraciətinizə {code} dizayn kodunu və spesifikasiyasını əlavə edir.",
    consent: "Configuro-nun bu müraciətə cavab vermək üçün məlumatlarımı saxlamasına razıyam.",
    privacyLink: "Məlumatlarınızı necə istifadə edirik",
    submit: "Təklif istəyin",
    sending: "Göndərilir…",
    successTitle: "Müraciət qəbul edildi",
    successText: "Təşəkkürlər. Bir iş günü ərzində cavab veririk.",
    reference: "İstinad",
    another: "Yeni müraciət göndər",
    error: "Müraciətiniz göndərilmədi. Bağlantınızı yoxlayıb yenidən cəhd edin və ya hello@configuro.studio ünvanına yazın.",
    retry: "Yenidən cəhd et",
    emailInstead: "E-poçtla yazın",
    required: "Bu sahə mütləqdir.",
    badEmail: "Düzgün e-poçt daxil edin, məsələn nigar@sirket.az.",
    badUrl: "Düzgün sayt ünvanı daxil edin, məsələn sirket.az.",
    consentRequired: "Müraciətinizi saxlaya bilməyimiz üçün təsdiqləyin.",
    fixErrors: "Qeyd olunmuş sahələri düzəldin.",
  },

  privacyTitle: "Məxfilik",
  privacy: [
    "Təklif istədikdə daxil etdiyiniz məlumatları, əlavə etdiyiniz dizaynı və bu səhifəyə necə gəldiyinizi (məsələn, reklam kampaniyası etiketi) toplayırıq. Onlardan yalnız müraciətinizə cavab vermək və təklif hazırlamaq üçün istifadə edirik.",
    "Müraciətlər Configuro-nun müştəri bazasında və CRM sistemində saxlanılır. Analitika və reklam ölçümü yalnız qəbul etsəniz yüklənir və adınızı, e-poçtunuzu və ya mesajınızı heç vaxt almır.",
    "Məlumatlarınızı görmək və ya sildirmək üçün hello@configuro.studio ünvanına yazın.",
  ],
  consentText: "Hansı kampaniyaların faydalı müraciətlər gətirdiyini öyrənmək üçün analitika və reklam ölçümündən istifadə edirik. Yalnız qəbul etsəniz yüklənir.",
  consentAccept: "Qəbul et",
  consentDecline: "İmtina et",
  consentSettings: "Məxfilik ayarları",

  footerNote: "Configuro 3D konfiquratorlar dizayn edir və hazırlayır. Perqola təsvirləri və demo məhsullar nümunədir.",
  footerLinks: { services: "Xidmətlər", work: "İşlər", guide: "Konfiqurator bələdçisi", contact: "Əlaqə" },
};

export const COPY = { en: { ...en, ...STORY_COPY.en }, tr: { ...tr, ...STORY_COPY.tr }, az: { ...az, ...STORY_COPY.az } };
export const LANGUAGES = ["en", "tr", "az"];
export const format = (template, values) => String(template).replace(/\{(\w+)\}/g, (_, key) => values[key] ?? "");
